item {
  id: 1
  name: 'k'
}
item {
  id: 2
  name: 'kh'
}
item {
  id: 3
  name: 'g'
}
item {
  id: 4
  name: 'gh'
}
item {
  id: 5
  name: 'ch'
}
item {
  id: 6
  name: 'chh'
}
item {
  id: 7
  name: 'j'
}
item {
  id: 8
  name: 'jh'
}
item {
  id: 9
  name: 't'
}
item {
  id: 10
  name: 'th'
}
item {
  id: 11
  name: 'd'
}
item {
  id: 12
  name: 'dh'
}
item {
  id: 13
  name: 'ana'
}
item {
  id: 14
  name: 'ta'
}
item {
  id: 15
  name: 'tha'
}
item {
  id: 16
  name: 'd'
}
item {
  id: 17
  name: 'dha'
}
item {
  id: 18
  name: 'n'
}
item {
  id: 19
  name: 'p'
}
item {
  id: 20
  name: 'ph'
}
item {
  id: 21
  name: 'b'
}
item {
  id: 22
  name: 'bh'
}
item {
  id: 23
  name: 'm'
}
item {
  id: 24
  name: 'y'
}
item {
  id: 25
  name: 'r'
}
item {
  id: 26
  name: 'l'
}
item {
  id: 27
  name: 'v'
}
item {
  id: 28
  name: 's'
}
item {
  id: 29
  name: 'sh'
}
item {
  id: 30
  name: 'shh'
}
item {
  id: 31
  name: 'h'
}
item {
  id: 32
  name: 'ala'
}
item {
  id: 33
  name: 'ksh'
}
item {
  id: 34
  name: 'gna'
}
